site_name: Documentation of twinsphere Suite by conplement AG
site_url: https://docs.aas.conplement.cloud
theme:
  name: readthedocs
  locale: en
  logo: img/twinsphere-logo.png
  palette:
    primary: green
extra_css:
- css/extra.css
nav:
  - Home: index.md
  - Contact us: contact.md
  - twinsphere ID:
    - Overview: id-overview.md
  - Cloud:
    - API Documentation: cloud-documentation.md
    - Proprietary Features:
      - Overview: cloud-proprietary-features.md
      - Change Events: cloud-change-events.md
      - Search: cloud-search.md
      - Push Service: cloud-push-service.md
      - Semantic Connector: cloud-semantic-connector.md
      - Filter Queries: cloud-filter-queries.md
    - Authentication: cloud-auth.md
    - Client Generation: cloud-client-generation.md
    - Release Notes: cloud-release-notes.md
  - Studio:
    - Overview: studio-overview.md
    - General Features: studio-general-features.md
    - Catalog: studio-catalog.md
    - Twin Builder: studio-twin-builder.md
    - Release Notes: studio-release-notes.md
  - Viewer:
    - Overview: viewer-overview.md
    - Features: viewer-features.md
    - Release Notes: viewer-release-notes.md
  - Management API:
    - Overview: management-overview.md
    - Roles: management-roles.md
  - Development Libraries:
    - Overview: typed-aas-metamodels-overview.md
    - Supported Submodels: typed-aas-metamodels-submodels.md
    - Validation Rules: typed-aas-metamodels-validation.md
    - Release Notes: typed-aas-metamodels-release_notes.md
  - Validators:
    - Overview: validators-overview.md
  - Tips & Tricks:
    - Common Validation Errors: tips-common-validation-errors.md
copyright: Copyright &copy; 2025 <a href="https://www.conplement.de/twinsphere" taget="_blank">conplement AG</a>
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
markdown_extensions:
  - admonition
  - attr_list
  - admonition
plugins:
  - search
  - open-in-new-tab
  - link-marker
  - spellcheck:
      backends:
      - codespell:
          dictionaries: [clear, rare, informal, usage, en-GB_to_en-US]
      known_words: known_words.txt
      ignore_code: yes
      allow_unicode: yes
      strict_only: yes
